Repository angelikavilde/SudokuSubscription, pull requests merged in 2023-10, with the labels that each got.

#6 Verified sudoku solver and improved runtime
  sudoku_solver.py
Labels: bug, enhancement

#7 Adding unit tests for sudoku solver
  sudoku_solver.py
  test_sudoku_solver.py
Labels: first pr, tests

#8 moved the test_sudoku to not be a global variable
  sudoku_solver.py
Labels: enhancement
